config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]
  resources :transactions, only: [:new, :create, :index, :show]
  resources :categories, only: [:index, :show, :new, :create] do
    resources :transactions, only: [:index, :show]
  end

  # Defines the root path route ("/")
  root "categories#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :transactions

  validates :name, presence: true, length: { maximum: 250 }
  validates :icon, presence: true, length: { maximum: 250 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    @transactions = Transaction.where(category_id: params[:id])
  end

  # GET /categories/1 or /categories/1.json
  def show
    @transactions = Transaction.where(category_id: params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon, :user_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <div class="d-flex justify-content-between bg-secondary-subtle p-3 rounded align-items-center">
    <div class="d-flex flex-row justify-content-between align-items-center">
    <p class="link-underline-light text-decoration-none">
    <%= image_tag category.icon, class: "img-thumbnail", alt: "icon" %>
    </p>
    <p class="text-decoration-none mx-5 fs-3 text-black">
      <%= category.name %>
    </p>
    </div>
    <p class="text-decoration-none text-black fs-3">
    <% if category.transactions.present? %>
        <% total_amount = 0 %>
        <% category.transactions.each do |transaction| %>
          <% total_amount += transaction.amount %>
        <% end %>
        <%= total_amount %>
            <% else %>
      <%= 0 %>
    <% end %>
      </p>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name,class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :icon, class:"form-label" %>
    <%= form.text_field :icon,class:"form-control" %>
  </div>

  <div>
    <%= form.submit "Save", class:"btn btn-sucess mb-3 bg-primary text-white", style: "width: 100%; margin: auto;"%>
  </div>
<% end %>

app/views/categories/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary", style="width: 100%; ">
  <div class="container-fluid p-2 px-3 bg-primary text-white">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
          <li class="nav-item">
          <% if user_signed_in? %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link text-white", "data-turbo-method": :delete %>
          <% else %>
          <div class="d-flex text-white">
          <%= link_to "Sign In", new_user_session_path , class: "nav-link text-white"%>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link text-white"%>
          </div>
          <% end %>
          </li>   
      </ul>
    </div>
  </div>
</nav>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<% if user_signed_in? %>
<%= render "categories/navbar" %>
<% end %>
<div container align-items-center>
<p style="color: green"><%= notice %></p>

<% if user_signed_in? %>
  <h1 class="text-center">Categories</h1>
  <div id="categories">
    <% @categories.each do |category| %>
      <p >
        <%= link_to category_transactions_path(category) do %>
          <%= render partial: "category", locals: { category: category } %>
        <% end %>
      </p>
    <% end %>
  </div>
  <%= link_to "New category", new_category_path, class: "btn btn-sucess mb-3 mx-3 text-white", style: "width: 85%; margin: auto; background-color: #60B525; position: absolute; bottom: 0;" %>

<% else %>
  <div class="container" style="margin-top: 6rem;">
  <div class="column ">
  <div class="text-center my-3">
  <%= image_tag("logo.png", class: "rounded mx-auto d-block", style: "width: 20rem") %>
  </div>
  <div class="text-center d-flex justify-content-center flex-column">
  <%= link_to "Sign In", new_user_session_path , class:"btn icon-link-hover btn-sucess mb-3 bg-primary text-white", style:"margin-top: 6rem;"%>
  <%= link_to "Sign up", new_user_registration_path, class:"btn btn-sucess mb-3 bg-primary text-white"%>
  </div>
  </div>
  </div>
<% end %>
</div>

app/views/categories/new.html.erb
<div style="margin-top: 6rem;">
<h4>New category</h4>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back", categories_path %>
</div>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>Transactions</h1>

<div id="transactions">
  <% @transactions.each do |transaction| %>
       <%= render category_transactions_path %>
    <p>
      <%= link_to "Show this transaction", transaction %>
    </p>

  <% end %>
</div>

<div>
  <%= link_to "Back to categories", categories_path %>

</div>

<%= link_to "New transaction", new_transaction_path %>