config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]
  resources :transactions, only: [:new, :create, :index, :show]
  resources :categories, only: [:index, :show, :new, :create] do
    resources :transactions, only: [:index, :show]
  end

  # Defines the root path route ("/")
  root "categories#index"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  # GET /transactions or /transactions.json
  def index
    @category_id = params[:category_id]
    @transactions = Transaction.where(category_id: @category_id).order(created_at: :desc)
    @total_amount = 0
    @transactions.each do |transaction|
      @total_amount += transaction.amount
    end
  end

  # GET /transactions/1 or /transactions/1.json
  def show
    @category_id = params[:category_id]
    @transactions = Transaction.all
    @transaction = Transaction.where(id: params[:id])
    @transaction_cat_id = @transaction.first.category_id
    @category = Category.where(id: @category_id)
    @total_amount = 0
    @transactions.each do |transaction|
      @total_amount += transaction.amount
    end
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    @categories = Category.all
  end

  # GET /transactions/1/edit
  def edit; end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = current_user
    @category_id = params[:category_id]

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to category_transactions_url(@transaction.category_id) }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:name, :amount, :user_id, :category_id)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name ,class:"form-control"%>
  </div>

  <div class="mb-3">
    <%= form.label :amount, class:"form-label" %>
    <%= form.text_field :amount, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :categories, class:"form-label" %>
    <%= form.select :category_id, options_for_select(@categories.map { |category| [category.name, category.id] }),class:"form-control" %>
  </div>

  <div>
    <%= form.submit "Save", class:"btn btn-sucess mb-3 bg-primary", style: "width: 100%; margin: auto;" %>
  </div>
<% end %>

app/views/transactions/_single_transaction.html.erb
<div id="<%= dom_id transaction %>">
<div class="p-3 rounded my-3">
  
  <p class="">
    <%= transaction.name %>
  </p>
  <p class="">
    <%= "Total Amount: #{transaction.amount}" %>
  </p>
</div>
</div>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
<div class="d-flex justify-content-between bg-secondary-subtle p-3 rounded my-3">
  <p class="text-decoration-none mx-5 fs-3 text-black">
    <%= transaction.name %>
  </p>

  <p class="text-decoration-none mx-5 fs-3 text-black">
    <%= transaction.amount %>
  </p>
</div>
</div>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Show this transaction", @transaction %> |
  <%= link_to "Back to transactions", transactions_path %>
</div>

app/views/transactions/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="bg-primary rounded px-3 pt-3 d-flex align-items-center" style="width: 100%; height: 3rem;">
<%= link_to categories_path, class: "mb-3 fs-4" do %>
  <%= image_tag("left-arrow.png", class: "rounded d-block", style: "width: 2rem") %>
<% end %>
</div>
<div class="d-flex justify-content-between px-4 fs-3" >
<h4>Transactions</h4>
<%= "Total amount:  #{@total_amount}" %>
</div>
<div id="transactions">
  <% @transactions.each do |transaction| %>
    <p >
    <%= link_to transaction_path(transaction) do %>
      <%= render partial: "transaction", locals: { transaction: transaction } %>
    <% end %>
  </p>
  <% end %>
</div>

<%= link_to "New transaction", new_transaction_path, class:"btn btn-sucess mb-3 mx-3 text-white fs-5",style: "width: 85%; margin: auto; background-color: #60B525; position: absolute; bottom: 0;" %>

app/views/transactions/new.html.erb
<div style="margin-top: 6rem;">
<h1>New transaction</h1>

<%= render "form", transaction: @transaction %>

<br>

<div>
  <%= link_to "Back to transactions", transactions_path %>
</div>
</div>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
<%= link_to "Back", category_transactions_path(@transaction_cat_id), class:"btn btn-sucess mb-3 bg-primary fs-4 text-white" %>
</div>
<div id="transactions">
  <% @transactions.each do |transaction| %>
    <%= render partial: "single_transaction", locals: { transaction: transaction } %>
  <% end %>
</div>